version: 3.0.{build}

environment:
  api_key:
    secure: 9f1tfKfxrHOsDPxKcstzU46FndPSu5/oPdKRRuLB4MF+eh8cA2TOKH0cvmxWQ2P5
  api_key_smbsrc:
    secure: 3yeXDeY9MuDPEp+VqFU5M3hp7Oqbaq9Evkxyi55rmzUb14IfqCbNYrQJhw4VV8YD

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
test: off

#deploy:
#- provider: NuGet
#  api_key:
#    secure: 9f1tfKfxrHOsDPxKcstzU46FndPSu5/oPdKRRuLB4MF+eh8cA2TOKH0cvmxWQ2P5
#  skip_symbols: true

deploy_script:
  # download latest nuget
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  
  # publish packages  
  - nuget.exe setApiKey %api_key% -source https://www.nuget.org
  - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package; if ($lastexitcode -ne 0) {throw}}
  
  # publish symbols if needed
  - nuget.exe setApiKey %api_key_smbsrc% -source https://nuget.smbsrc.net
  - ps: ($artifacts.values | Where-Object {$_.path -like '*.symbols.nupkg'}) | foreach-object {nuget.exe push $_.path -Source https://nuget.smbsrc.net/api/v2/package; if ($lastexitcode -ne 0) {throw}}

