version: 3.0.{build}

environment:
  api_key:
    #secure: 9f1tfKfxrHOsDPxKcstzU46FndPSu5/oPdKRRuLB4MF+eh8cA2TOKH0cvmxWQ2P5
    secure: 8SJ88BfGDKVlkLC5kG5UqyRhdK0ouh9ljmiILAjVqKU2Lhs0CHUY2F/YQ2UuyGS1

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
test: off

#deploy:
#- provider: NuGet
#  api_key:
#    secure: 9f1tfKfxrHOsDPxKcstzU46FndPSu5/oPdKRRuLB4MF+eh8cA2TOKH0cvmxWQ2P5
#    secure: 8SJ88BfGDKVlkLC5kG5UqyRhdK0ouh9ljmiILAjVqKU2Lhs0CHUY2F/YQ2UuyGS1
#  skip_symbols: true

deploy_script:
  # download latest nuget
 # - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget update -self
  # publish packages  
  - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -ApiKey $env:api_key; if ($lastexitcode -ne 0) {throw}}
